# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fengqin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fengqin_assitant(object):
    def setupUi(self, fengqin_assitant):
        fengqin_assitant.setObjectName("fengqin_assitant")
        fengqin_assitant.resize(351, 261)
        self.gridLayout = QtWidgets.QGridLayout(fengqin_assitant)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gb_toolbar = QtWidgets.QGroupBox(fengqin_assitant)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_toolbar.sizePolicy().hasHeightForWidth())
        self.gb_toolbar.setSizePolicy(sizePolicy)
        self.gb_toolbar.setTitle("")
        self.gb_toolbar.setObjectName("gb_toolbar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_toolbar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_play = QtWidgets.QPushButton(self.gb_toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_play.sizePolicy().hasHeightForWidth())
        self.pb_play.setSizePolicy(sizePolicy)
        self.pb_play.setObjectName("pb_play")
        self.verticalLayout_2.addWidget(self.pb_play)
        self.pb_stop = QtWidgets.QPushButton(self.gb_toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_stop.sizePolicy().hasHeightForWidth())
        self.pb_stop.setSizePolicy(sizePolicy)
        self.pb_stop.setObjectName("pb_stop")
        self.verticalLayout_2.addWidget(self.pb_stop)
        self.pb_edit = QtWidgets.QPushButton(self.gb_toolbar)
        self.pb_edit.setObjectName("pb_edit")
        self.verticalLayout_2.addWidget(self.pb_edit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.gb_toolbar, 0, 1, 1, 1)
        self.lw_song = QtWidgets.QListWidget(fengqin_assitant)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lw_song.sizePolicy().hasHeightForWidth())
        self.lw_song.setSizePolicy(sizePolicy)
        self.lw_song.setObjectName("lw_song")
        self.gridLayout.addWidget(self.lw_song, 0, 0, 1, 1)

        self.retranslateUi(fengqin_assitant)
        QtCore.QMetaObject.connectSlotsByName(fengqin_assitant)

    def retranslateUi(self, fengqin_assitant):
        _translate = QtCore.QCoreApplication.translate
        fengqin_assitant.setWindowTitle(_translate("fengqin_assitant", "风琴小助手"))
        self.pb_play.setText(_translate("fengqin_assitant", "开始"))
        self.pb_stop.setText(_translate("fengqin_assitant", "停止"))
        self.pb_edit.setText(_translate("fengqin_assitant", "编写"))
