# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\lyre_assitant.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lyre_assitant(object):
    def setupUi(self, lyre_assitant):
        lyre_assitant.setObjectName("lyre_assitant")
        lyre_assitant.resize(351, 261)
        self.gridLayout = QtWidgets.QGridLayout(lyre_assitant)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gb_toolbar = QtWidgets.QGroupBox(lyre_assitant)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_toolbar.sizePolicy().hasHeightForWidth())
        self.gb_toolbar.setSizePolicy(sizePolicy)
        self.gb_toolbar.setTitle("")
        self.gb_toolbar.setObjectName("gb_toolbar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_toolbar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_play = QtWidgets.QPushButton(self.gb_toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_play.sizePolicy().hasHeightForWidth())
        self.pb_play.setSizePolicy(sizePolicy)
        self.pb_play.setObjectName("pb_play")
        self.verticalLayout_2.addWidget(self.pb_play)
        self.pb_stop = QtWidgets.QPushButton(self.gb_toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_stop.sizePolicy().hasHeightForWidth())
        self.pb_stop.setSizePolicy(sizePolicy)
        self.pb_stop.setObjectName("pb_stop")
        self.verticalLayout_2.addWidget(self.pb_stop)
        self.pb_edit = QtWidgets.QPushButton(self.gb_toolbar)
        self.pb_edit.setObjectName("pb_edit")
        self.verticalLayout_2.addWidget(self.pb_edit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.gb_toolbar, 0, 1, 1, 1)
        self.tw_song = QtWidgets.QTableWidget(lyre_assitant)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_song.sizePolicy().hasHeightForWidth())
        self.tw_song.setSizePolicy(sizePolicy)
        self.tw_song.setObjectName("tw_song")
        self.tw_song.setColumnCount(2)
        self.tw_song.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_song.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_song.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tw_song, 0, 0, 1, 1)

        self.retranslateUi(lyre_assitant)
        QtCore.QMetaObject.connectSlotsByName(lyre_assitant)

    def retranslateUi(self, lyre_assitant):
        _translate = QtCore.QCoreApplication.translate
        lyre_assitant.setWindowTitle(_translate("lyre_assitant", "风琴小助手"))
        self.pb_play.setText(_translate("lyre_assitant", "开始"))
        self.pb_stop.setText(_translate("lyre_assitant", "停止"))
        self.pb_edit.setText(_translate("lyre_assitant", "编写"))
        item = self.tw_song.horizontalHeaderItem(0)
        item.setText(_translate("lyre_assitant", "name"))
        item = self.tw_song.horizontalHeaderItem(1)
        item.setText(_translate("lyre_assitant", "path"))
